### ISSUE TITLE
nguibs-dropdown in a button with a color scheme having lightondark=true 

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-ui#10]
is ugly because of text-shadow

`_buttons.less` line 171
```less
& when (@lightOnDark = true) {
	text-shadow: 0 1px 1px darken(@color, 5);
}
```

the text-shadow barely noticeable inside a button but if you have something like this, you see the text-shadow on a white background and it is not pretty
```html
<div class="lui red button nguibs-dropdown" dropdown dropdown-toggle>
	<span>i cant see no text-shadow on this button</span>
	<ul class="dropdown-menu">
		<li>
			<a>dis iz ugly</a>
		</li>
		<li>
			<a>i iz sad :'(</a>
		</li>
	</ul>
</div>
```
