### ISSUE TITLE
`.right-aligned` not working inside a `lui table`

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-ui#7]
`.lui.table>.thead>.tr>.th` et `.lui.table>tbody>tr>td` have `text-align:left;` that gets applied over the `text-align` of classes `.left-aligned`, `.center-aligned`, `.right-aligned` and `justify-aligned`.

for reference, `.xxx-aligned` is defined in /core/definitions/_typography.less, line ~85 and `lui table` in /core/elements/_table.less line ~22

also there's this
```less 
.lui.table{
	...
	&.center-align {
        text-align: center;
	}
	&.left-align {
		text-align: left;
	}
	&.right-align {
    	text-align: right;
	}
	&.justified-align {
		text-align: justify;
	}
}
```
it's not coherent to have `.right-aligned` and `.right-align` as available classes

also this class is applied to the whole lui table and that's not what i'm after, i want to have some cells right-aligned and some other left-aligned

also i'm not sure it works as intended because you have this
```less
.lui.table{
  > .thead > .tr > .th, > .tbody > .tr > .td, > thead > tr > th, > tbody > tr > td {
    text-align: left;
  }
  &.right-align{
    text-align: right;
  }
}
```
so i think the rule for a cell overrides the rule for the table
